mysite/agenda/urls.py
from django.urls import path

from . import views

app_name = 'agenda'
urlpatterns = [
    # ex: /agenda/
    path('', views.especialidades, name='especialidades'),
    path('medicos', views.medicos, name='medicos'),
    path('agendar_hora', views.agendar_hora, name='agendar'),
    # ex: /agenda/login
    # path('login', views.login, name='login'),
    # ex: /agenda/logout
    path('logout', views.logout, name='logout'),
    # ex: /agenda/especialidad/5
    #path('<int:especialidad_id>/', views.medicos, name='medicos'),
    # ex: /agenda/medico/5
    path('medico/<int:medico_id>/', views.medico, name='medico'),
    # ex: /polls/5/results/
    #path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    #path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView  # new

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),  # new
    path('agendar/', include('agenda.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
]

mysite/agenda/models.py
from django.db import models
from django.utils import timezone
import datetime


class Perfil(models.Model):
    password = models.CharField(max_length=200)
    level = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Usuario(models.Model):
    nombres = models.CharField(max_length=200)
    apellidos = models.CharField(max_length=200)
    fecha_nacimiento = models.DateField()
    email = models.EmailField(max_length=200)
    fono = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    perfil = models.ForeignKey(
        Perfil, on_delete=models.SET_NULL, default=None, null=True)

    class Meta:
        abstract = True


class Especialidad(models.Model):
    descripcion = models.CharField(max_length=200)

    def __str__(self):
        return self.descripcion


class Medico(Usuario):

    especialidad = models.ForeignKey(
        Especialidad, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return 'Dr/a. ' + self.nombres + '' + self.apellidos


class Paciente(Usuario):
    def __str__(self):
        return 'Sr/a/ita.' + self.nombres + '' + self.apellidos


class Agenda(models.Model):
    fecha = models.DateField()
    hora_desde = models.TimeField()
    hora_hasta = models.TimeField()
    medico = models.ForeignKey(Medico, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    disponible = models.BooleanField(default=True)

    def __str__(self):
        return self.medico.nombres + self.medico.apellidos + ': ' + str(self.fecha) + ' ' + str(self.hora_desde) + ' - ' + str(self.hora_hasta)

    def is_expired(self):
        return self.fecha >= timezone.now().date - datetime.timedelta(days=1)


class Cita(models.Model):
    agenda = models.ForeignKey(Agenda, on_delete=models.SET_NULL, null=True)
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.paciente.nombres + self.paciente.apellidos + ' ' + self.agenda.fecha + ' ' + self.agenda.hora_desde + ' - ' + self.agenda.hora_hasta + ' médico: ' + self.agenda.medico.apellidos

mysite/agenda/views.py
import json
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.urls import reverse
from datetime import date, timedelta

from .models import Cita, Especialidad, Medico, Agenda


# @login_required
def especialidades(request):
    especialidades_all_list = Especialidad.objects.order_by('-descripcion')
    medicos_all_list = Medico.objects.all()
    context = {'especialidades_all_list': especialidades_all_list,
               'medicos_all_list': medicos_all_list,
               'medicos_url': reverse('agenda:medicos')
               }
    return render(request, 'agenda/especialidades.html', context)


def getMedicoByEspecialidad(self, *args, **kwargs):
    filter_category = self.request.GET.get("filter_category")
    queryset = Medico.objects.filter(Especialidad=filter_category)
    queryset_filtered = queryset.filter()
    return queryset_filtered


def agendar(request):
    especialidades_all_list = Especialidad.objects.order_by('-descripcion')
    medicos_all_list = Medico.objects.all()
    context = {'especialidades_all_list': especialidades_all_list,
               'medicos_all_list': medicos_all_list}
    return render(request, 'agenda/agendar.html', context)


def agendar_hora(request):
    if request.method == 'POST':
        hora_id = request.POST['flexRadioDefault']
        paciente = request.POST['user_id']

        cita = Cita(agenda_id=hora_id, paciente_id=paciente)
        cita.save()
    return render(request, 'home.html')


def medicos(request):
    data = json.loads(request.body)
    medicos = Medico.objects.filter(especialidad__id=data['id'])
    # print(medicos)
    return JsonResponse(list(medicos.values("id", "nombres", "apellidos")), safe=False)


def medico(request, medico_id):
    medico = get_object_or_404(Medico, pk=medico_id)
    startdate = date.today()
    enddate = startdate + timedelta(days=6)
    result = Agenda.objects.filter(
        fecha__range=[startdate, enddate], medico__id=medico.id)
    agenda = [[], []]
    for row in result:
        if row.fecha == startdate:
            agenda[0].append(row)
        else:
            agenda[1].append(row)

    return render(request, 'agenda/horas.html', {'medico': medico, 'agenda': agenda})


def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)


def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return HttpResponseRedirect('/agenda/')
        else:
            # Return an 'invalid login' error message.
            return HttpResponseRedirect('/agenda/')
    else:
        return render(request, 'agenda/login.html')


""" def login(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, 'form.html', {'form': form}) """


@login_required
def logout(request):
    logout(request)
    # Redirect to a success page.

mysite/agenda/templates/agenda/especialidades - copia.html
<!-- templates/registration/login.html -->
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}

<section id="services" class="services">
    <div class="container">

      <div class="section-title">
        <h2>Especialidades</h2>
        <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
      </div>

      {% if especialidades_all_list %}
      <div class="row">

        {% for especialidad in especialidades_all_list %}
        <div class="col-lg-4 col-md-6 d-flex align-items-stretch mb-4">
          <div class="icon-box">
            <div class="icon"><i class="fas fa-heartbeat"></i></div>
            <h4><a href="{% url 'agenda:medicos' especialidad.id %}">{{ especialidad.descripcion }}</a></h4>
            <p>Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi</p>
          </div>
        </div>
        {% endfor %}

      </div>
      {% else %}
        <p>No polls are available.</p>
      {% endif %}
    </div>
  </section>
{% endblock %}

mysite/agenda/templates/agenda/especialidades.html
<!-- templates/registration/login.html -->
{% extends 'base.html' %}

{% block title %}Login{% endblock %}


{% block content %}
{{ medicos_url|json_script:"url-med" }}
<section id="especialidades" class="services">
  <div class="container">

    <div class="section-title">
      <h2>Especialidades</h2>
      <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
    </div>

    {% if especialidades_all_list %}
    <div class="row" id="especialidadesRow">
      <input type="text" id="filterSearch" onkeyup="filterItems()" placeholder="Search for names.." title="Type in a name">
      {% for especialidad in especialidades_all_list %}
        <div class="col-lg-3 col-md-4 align-items-stretch mb-4 especialidad-item item-{{ especialidad.id }}">
          <div onclick="clickedItem('{{especialidad.id}}', '{{especialidad.descripcion}}')">
            <div class="icon-box">
              <div class="icon"><i class="fas fa-heartbeat"></i></div>
              <h4><a href="#doctors">{{ especialidad.descripcion }}</a></h4>
            </div>
          </div>
        </div>
      {% endfor %}

    </div>
    {% else %}
      <p>No polls are available.</p>
    {% endif %}
  </div>
</section>

<section id="doctors" class="doctors">
  <div class="container">

    <div class="section-title">
      <h2>Doctors</h2>
      <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
    </div>

    {% if medicos_all_list %}
    <div class="row" id="medicos_row">
      {% for medico in medicos_all_list %}
      <div class="col-lg-6">
        <div class="member d-flex align-items-start">
          <div class="pic"><img src="/static/assets/img/doctors/doctors-1.jpg" class="img-fluid" alt=""></div>
          <div class="member-info">
            <h4>Walter White</h4>
            <span>{{ medico.especialidad }}</span>
            <p>Explicabo voluptatem mollitia et repellat qui dolorum quasi</p>
            <a href="{% url 'agenda:medico' medico.id %}">Agendar Hora</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% else %}
      <p>No polls are available.</p>
    {% endif %}

  </div>
</section>
{% endblock %}

mysite/agenda/templates/agenda/horas - copia.html
{% extends 'base.html' %}

{% block content %}
<section id="doctors" class="doctors">
<div class="container">
    <div class="row">

        <div class="col-lg-12">
          <div class="member d-flex align-items-start">
            <div class="pic"><img src="/static/assets/img/doctors/doctors-1.jpg" class="img-fluid" alt=""></div>
            <div class="member-info">
              <h4>{{medico.nombres}} {{medico.apellidos}}</h4>
              <span>{{medico.especialidad}}</span>
              <p>Explicabo voluptatem mollitia et repellat qui dolorum quasi</p>
              <div class="social">
                <a href=""><i class="ri-twitter-fill"></i></a>
                <a href=""><i class="ri-facebook-fill"></i></a>
                <a href=""><i class="ri-instagram-fill"></i></a>
                <a href=""> <i class="ri-linkedin-box-fill"></i> </a>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>
</section>
<section id="faq" class="faq" style="padding-top: 0;">
    <div class="container">

      <div class="section-title">
        <h2>Horas disponibles</h2>
        <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
      </div>

      <div class="faq-list">
        {% if agenda %}

            <h3>Hoy</h3>
            {% if agenda.0|length > 0 %}
            <ul class="agenda-list">
                {% for hora in agenda.0 %}
                    <li>
                        <i class="bx bx-help-circle icon-help"></i> <a class="collapse">{{ hora.fecha }} {{hora.hora_desde}} - {{hora.hora_hasta}}<button class="agendar-btn">Agendar</button></a>
                        <div id="faq-list-1" class="collapse" data-bs-parent=".faq-list" style="">
                            <p>{{ hora.fecha }} {{hora.hora_desde}} - {{hora.hora_hasta}}</p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            {% else %}
            <h4>No hay horas disponibles.</h4>
            {% endif %}

            <h3>Semana</h3>
            {% if agenda.1|length > 0 %}
            <ul>
                {% for hora in agenda.1 %}
                    <li data-aos="fade-up">
                        <i class="bx bx-help-circle icon-help"></i> <a>{{ hora.fecha }} {{hora.hora_desde}} - {{hora.hora_hasta}}<i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
                    </li>
                {% endfor %}
            </ul>
            {% else %}
            <h4>No hay horas disponibles.</h4>
            {% endif %}

        {% else %}
        <h4>No hay horas disponibles.</h4>
        {% endif %}
      </div>

    </div>
</section>
{% endblock %}

mysite/agenda/templates/agenda/horas.html
{% extends 'base.html' %}

{% block content %}
<section id="doctors" class="doctors">
<div class="container">
    <div class="row">

        <div class="col-lg-12">
          <div class="member d-flex align-items-start">
            <div class="pic"><img src="/static/assets/img/doctors/doctors-1.jpg" class="img-fluid" alt=""></div>
            <div class="member-info">
              <h4>{{medico.nombres}} {{medico.apellidos}}</h4>
              <span>{{medico.especialidad}}</span>
              <p>Explicabo voluptatem mollitia et repellat qui dolorum quasi</p>
              <div class="social">
                <a href=""><i class="ri-twitter-fill"></i></a>
                <a href=""><i class="ri-facebook-fill"></i></a>
                <a href=""><i class="ri-instagram-fill"></i></a>
                <a href=""> <i class="ri-linkedin-box-fill"></i> </a>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>
</section>
<section id="faq" class="departments" style="padding-top: 0;">
    <div class="container">

        <div class="row gy-4">
            <div class="col-lg-3">
              <ul class="nav nav-tabs flex-column" role="tablist">
                <li class="nav-item" role="presentation">
                  <a class="nav-link show active" data-bs-toggle="tab" href="#tab-1" aria-selected="true" role="tab">Seleccionar Hora</a>
                </li>
                <li class="nav-item" role="presentation">
                  <a class="nav-link" data-bs-toggle="tab" href="#tab-2" aria-selected="false" role="tab" tabindex="-1">Ingresar Datos</a>
                </li>
                <li class="nav-item" role="presentation">
                  <a class="nav-link" data-bs-toggle="tab" href="#tab-3" aria-selected="false" role="tab" tabindex="-1">Confirmar Cita</a>
                </li>
              </ul>
            </div>
            <div class="col-lg-9">
              <form action="/agendar/agendar_hora" method="post" class="php-email-form">
                {% csrf_token %}
                <div class="tab-content">
                  <div class="tab-pane active show" id="tab-1" role="tabpanel">
                    
                      <section id="faq" class="faq" style="padding-top: 0;">
                          <div class="container">
                      
                            <div class="section-title">
                              <h2>Horas disponibles</h2>
                            </div>
                      
                            <div class="faq-list">
                              {% if agenda %}
                      
                                  <h3>Hoy</h3>
                                  {% if agenda.0|length > 0 %}
                                  <ul class="agenda-list">
                                      {% for hora in agenda.0 %}
                                          <li>
                                              <i class="bx bx-help-circle icon-help"></i> 
                                              <a class="collapse">{{ hora.fecha }} {{hora.hora_desde}} - {{hora.hora_hasta}}
                                                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault{{hora.id}}" value="{{hora.id}}">
                                              </a>
                                              <div id="faq-list-1" class="collapse" data-bs-parent=".faq-list" style="">
                                                  <p>{{ hora.fecha }} {{hora.hora_desde}} - {{hora.hora_hasta}}</p>
                                              </div>
                                          </li>
                                      {% endfor %}
                                  </ul>
                                  {% else %}
                                  <h4>No hay horas disponibles.</h4>
                                  {% endif %}
                      
                                  <h3>Semana</h3>
                                  {% if agenda.1|length > 0 %}
                                  <ul>
                                      {% for hora in agenda.1 %}
                                          <li data-aos="fade-up">
                                              <i class="bx bx-help-circle icon-help"></i> <a>{{ hora.fecha }} {{hora.hora_desde}} - {{hora.hora_hasta}}<i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
                                          </li>
                                      {% endfor %}
                                  </ul>
                                  {% else %}
                                  <h4>No hay horas disponibles.</h4>
                                  {% endif %}
                      
                              {% else %}
                              <h4>No hay horas disponibles.</h4>
                              {% endif %}
                            </div>
                      
                          </div>
                      </section>



                  </div>
                  <div class="tab-pane" id="tab-2" role="tabpanel">

                      <!-- ======= Appointment Section ======= -->
                      <section id="appointment" class="appointment" style="padding-top: 0;">
                        <div class="container">

                          <div class="section-title">
                            <h2>Ingrese sus datos</h2>
                          </div>

                          <div class="home-login">
                            {% if user.is_authenticated %}
                            Hola, {{ user.username }}!
                            <p><a href="{% url 'logout' %}">Log Out</a></p>
                            {% else %}
                            <h4>No ha iniciado sesión.</h4>
                            <p>Al iniciar sesión accede a beneficios exclusivos para usuarios registrados.</p>
                            <p>Si aún no posee una cuenta puede <a href="{% url 'login' %}">Registrarse</a>.</p>
                            <a id="myBtn_" class="login-a" href="{% url 'login' %}">Iniciar sesión</a>
                            {% endif %}
                          </div>

                            

                          
                          <div class="row">
                            <input type="text" name="user_id" id="user_id" value="{% if user %}{{user.id}}{% endif %}">
                            <div class="col-md-4 form-group">
                              <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" value="{% if user %}{{user.first_name}} {{user.last_name}}{% endif %}">
                              <div class="validate"></div>
                            </div>
                            <div class="col-md-4 form-group mt-3 mt-md-0">
                              <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" value="{% if user %}{{user.email}}{% endif %}">
                              <div class="validate"></div>
                            </div>
                            <div class="col-md-4 form-group mt-3 mt-md-0">
                              <input type="tel" class="form-control" name="phone" id="phone" placeholder="Your Phone" value="{% if user %}+56{% endif %}">
                              <div class="validate"></div>
                            </div>
                          </div>

                          <div class="form-group mt-3">
                            <textarea class="form-control" name="message" rows="5" placeholder="Message (Optional)"></textarea>
                            <div class="validate"></div>
                          </div>
                          <!--<div class="mb-3">
                            <div class="loading">Loading</div>
                            <div class="error-message"></div>
                            <div class="sent-message">Your appointment request has been sent successfully. Thank you!</div>
                          </div>
                          -->
                          
                          

                        </div>
                      </section><!-- End Appointment Section -->

                  </div>
                  <div class="my-3">
                    <div class="loading">Loading</div>
                    <div class="error-message"></div>
                    <div class="sent-message">Your message has been sent. Thank you!</div>
                  </div>
                  <div class="text-center"><button type="submit">Agendar</button></div>
                </div>
              </form>
            </div>
          </div>

    </div>
  </section>
{% endblock %}

mysite/agenda/templates/agenda/medicos.html
{% extends 'base.html' %}
{% block content %}
<section id="doctors" class="doctors">
    <div class="container">

      <div class="section-title">
        <h2>Doctors</h2>
        <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
      </div>

      <div class="row">
        {% for medico in especialidad.medico_set.all %}

        <li><a href="{% url 'agenda:medico' medico.id %}">{{ medico.nombres }}</a></li>


        <div class="col-lg-6">
          <div class="member d-flex align-items-start">
            <div class="pic"><img src="/static/assets/img/doctors/doctors-1.jpg" class="img-fluid" alt=""></div>
            <div class="member-info">
              <h4>Walter White</h4>
              <span>Chief Medical Officer</span>
              <p>Explicabo voluptatem mollitia et repellat qui dolorum quasi</p>
              <div class="social">
                <a href=""><i class="ri-twitter-fill"></i></a>
                <a href=""><i class="ri-facebook-fill"></i></a>
                <a href=""><i class="ri-instagram-fill"></i></a>
                <a href=""> <i class="ri-linkedin-box-fill"></i> </a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

      </div>

    </div>
  </section>
  {% endblock %}

mysite/agenda/templates/base_.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% load static %}
    <img src="{% static 'src/assets/media/photos/photo1.jpg' %}" alt="My image">
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>